"""Materialize a runnable Flutter project from build output (fast path vs emulator)."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

from ai_factory.fast_path import run_basic_agent
from ai_factory.utils import ARTIFACTS_DIR, save_artifact
from ai_factory.web_images import (
    apply_images_to_dart,
    build_image_prompt_block,
    labels_from_state,
    resolve_images_for_labels,
)

if TYPE_CHECKING:
    from ai_factory.models import AIFactoryState

PREVIEWS_DIR = Path("apps")
ALLOWED_PREFIXES = ("lib/", "pubspec.yaml", "README.md", "analysis_options.yaml")


@dataclass
class FlutterArtifactsResult:
    success: bool
    message: str
    project_dir: Path | None = None
    file_count: int = 0
    manifest_json: str = ""
    readme: str = ""
    files: list[str] = field(default_factory=list)
    log: str = ""


def artifacts_enabled() -> bool:
    return os.getenv("FLUTTER_ARTIFACTS", "1").strip().lower() not in ("0", "false", "no")


def _slug(name: str) -> str:
    slug = re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_")
    return slug[:30] or "ai_factory_app"


def _class_name(slug: str) -> str:
    name = "".join(part.capitalize() for part in slug.split("_") if part)
    if not name or not name[0].isalpha():
        name = f"App{name}"
    return name


def _extract_dart_blocks(markdown: str) -> list[str]:
    return [block.strip() for block in re.findall(r"```dart\s*\n(.*?)```", markdown, re.DOTALL)]


def _parse_project_json(raw: str) -> dict[str, Any]:
    start = raw.find("{")
    end = raw.rfind("}")
    if start < 0 or end <= start:
        raise ValueError("No JSON object in LLM response")
    return json.loads(raw[start : end + 1])


def _safe_relative_path(path: str) -> str | None:
    normalized = path.replace("\\", "/").lstrip("/")
    if ".." in normalized.split("/"):
        return None
    if not any(normalized == prefix.rstrip("/") or normalized.startswith(prefix) for prefix in ALLOWED_PREFIXES):
        return None
    return normalized


def flutter_project_prompt(state: AIFactoryState) -> str:
    image_block = build_image_prompt_block(
        run_id=state.run_id,
        client_brief=state.client_brief,
        requirements_doc=state.requirements_doc,
        code_artifacts=state.code_artifacts,
        project_name=state.project_name,
    )
    return f"""
Generate a minimal runnable Flutter MVP project for {state.project_name}.

PRD excerpt:
{state.requirements_doc[:3500]}

Build sketch:
{state.code_artifacts[:3500]}

Return ONLY valid JSON (no markdown fences):
{{
  "package_name": "snake_case_app_id",
  "files": [
    {{"path": "lib/main.dart", "content": "..."}},
    {{"path": "lib/models/product.dart", "content": "..."}},
    {{"path": "lib/screens/home_screen.dart", "content": "..."}}
  ]
}}

Rules:
- Include lib/main.dart with MaterialApp and navigation matching the PRD niche
- Include 3-5 screens under lib/screens/ with realistic product names from the PRD
- Include at least one model under lib/models/
- Use imageUrl values from WEB IMAGE URLS below (real web photos) — never picsum.photos
- Use only flutter SDK dependencies (no provider/riverpod unless essential)
- Valid Dart only — must compile with flutter analyze
- Max 8 files, total Dart under 450 lines
- No clarifying questions; output JSON only

{image_block}
""".strip()


def _default_pubspec(slug: str, title: str) -> str:
    return f"""name: {slug}
description: {title} — generated by AI Factory
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
"""


def _fallback_files(state: AIFactoryState, slug: str) -> list[dict[str, str]]:
    title = state.project_name.replace('"', "'")
    dart_blocks = _extract_dart_blocks(state.code_artifacts)
    screen_dart = dart_blocks[0] if dart_blocks else ""

    if "class " in screen_dart and "Widget build" in screen_dart:
        screen_path = "lib/screens/catalog_screen.dart"
        screen_file = screen_dart if screen_dart.startswith("import ") else f"import 'package:flutter/material.dart';\n\n{screen_dart}"
        home_widget = "CatalogScreen"
        if "class " in screen_dart:
            match = re.search(r"class\s+(\w+)\s+extends", screen_dart)
            if match:
                home_widget = match.group(1)
    else:
        screen_path = "lib/screens/home_screen.dart"
        screen_file = f"""import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {{
  const HomeScreen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(title: const Text('{title}')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: const [
          ListTile(
            leading: Icon(Icons.storefront),
            title: Text('Catalog'),
            subtitle: Text('Browse products from your PRD scope'),
          ),
          ListTile(
            leading: Icon(Icons.shopping_cart),
            title: Text('Cart'),
            subtitle: Text('Review items before checkout'),
          ),
          ListTile(
            leading: Icon(Icons.person),
            title: Text('Account'),
            subtitle: Text('Sign in or view order history'),
          ),
        ],
      ),
    );
  }}
}}
"""
        home_widget = "HomeScreen"

    app_class = _class_name(slug)
    main_dart = f"""import 'package:flutter/material.dart';
import 'screens/{Path(screen_path).stem}.dart';

void main() {{
  runApp(const {app_class}App());
}}

class {app_class}App extends StatelessWidget {{
  const {app_class}App({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{title}',
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF635BFF),
        useMaterial3: true,
      ),
      home: const {home_widget}(),
    );
  }}
}}
"""

    return [
        {"path": "pubspec.yaml", "content": _default_pubspec(slug, title)},
        {"path": "lib/main.dart", "content": main_dart},
        {"path": screen_path, "content": screen_file},
        {
            "path": "README.md",
            "content": (
                f"# {title} — Flutter MVP\n\n"
                "Generated by AI Factory from your PRD and build sketch.\n\n"
                "## Run locally\n\n"
                "```bash\n"
                "flutter pub get\n"
                "flutter run\n"
                "```\n"
            ),
        },
    ]


def _scaffold_project(project_dir: Path, slug: str) -> tuple[bool, str]:
    flutter = shutil.which("flutter")
    if not flutter:
        return False, "Flutter SDK not on PATH — writing source files only"

    if (project_dir / "pubspec.yaml").exists():
        return True, "Existing Flutter project reused"

    project_dir.parent.mkdir(parents=True, exist_ok=True)
    create = subprocess.run(
        [
            flutter,
            "create",
            "--org",
            "com.aifactory",
            "--project-name",
            slug,
            str(project_dir),
        ],
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    if create.returncode != 0:
        return False, (create.stderr or create.stdout or "flutter create failed")[:500]
    return True, "flutter create succeeded"


def _write_files(project_dir: Path, files: list[dict[str, str]]) -> list[str]:
    written: list[str] = []
    for item in files:
        rel = _safe_relative_path(str(item.get("path", "")))
        content = str(item.get("content", ""))
        if not rel or not content.strip():
            continue
        target = project_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(rel)
    return written


def _mirror_to_artifacts(project_dir: Path) -> Path:
    dest = ARTIFACTS_DIR / "build" / "flutter_project"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        project_dir,
        dest,
        ignore=shutil.ignore_patterns(".dart_tool", "build", ".idea", "*.iml"),
    )
    return dest


def _run_pub_get(project_dir: Path) -> str:
    flutter = shutil.which("flutter")
    if not flutter or not (project_dir / "pubspec.yaml").exists():
        return ""
    result = subprocess.run(
        [flutter, "pub", "get"],
        cwd=project_dir,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if result.returncode != 0:
        return (result.stderr or result.stdout or "")[:500]
    return ""


def _build_manifest(
    *,
    state: AIFactoryState,
    project_dir: Path,
    files: list[str],
    source: str,
    notes: str = "",
) -> str:
    payload = {
        "project_name": state.project_name,
        "run_id": state.run_id,
        "package_slug": _slug(state.project_name),
        "source": source,
        "project_dir": project_dir.as_posix(),
        "artifact_mirror": "artifacts/build/flutter_project",
        "files": files,
        "commands": [
            "cd apps/{run_id}/flutter",
            "flutter pub get",
            "flutter run",
        ],
        "notes": notes,
    }
    return json.dumps(payload, indent=2)


def generate_flutter_artifacts(state: AIFactoryState, run_id: str) -> FlutterArtifactsResult:
    """Create apps/{run_id}/flutter from PRD + build sketch."""
    if not artifacts_enabled():
        return FlutterArtifactsResult(
            success=False,
            message="Flutter artifacts disabled (set FLUTTER_ARTIFACTS=1)",
        )

    slug = _slug(state.project_name)
    project_dir = (PREVIEWS_DIR / run_id / "flutter").resolve()
    source = "llm"
    log_parts: list[str] = []

    scaffold_ok, scaffold_msg = _scaffold_project(project_dir, slug)
    log_parts.append(scaffold_msg)

    files_spec: list[dict[str, str]] = []
    try:
        raw = run_basic_agent(
            flutter_project_prompt(state),
            role="Flutter Engineer",
            goal="Emit a JSON Flutter project with lib/ source files.",
        )
        parsed = _parse_project_json(raw)
        package_name = str(parsed.get("package_name") or slug)
        slug = _slug(package_name)
        files_spec = list(parsed.get("files") or [])
        if not files_spec:
            raise ValueError("LLM JSON missing files array")
    except Exception as exc:
        source = "fallback_template"
        log_parts.append(f"LLM project generation failed: {exc}")
        files_spec = _fallback_files(state, slug)

    if not scaffold_ok and not any(f.get("path") == "pubspec.yaml" for f in files_spec):
        files_spec.insert(0, {"path": "pubspec.yaml", "content": _default_pubspec(slug, state.project_name)})

    written = _write_files(project_dir, files_spec)
    labels = labels_from_state(
        client_brief=state.client_brief,
        requirements_doc=state.requirements_doc,
        code_artifacts=state.code_artifacts,
        project_name=state.project_name,
    )
    image_map = resolve_images_for_labels(
        labels,
        run_id=run_id,
        client_brief=state.client_brief,
        requirements_doc=state.requirements_doc,
        code_artifacts=state.code_artifacts,
        project_name=state.project_name,
    )
    for dart_path in project_dir.rglob("*.dart"):
        original = dart_path.read_text(encoding="utf-8")
        updated = apply_images_to_dart(original, image_map)
        if updated != original:
            dart_path.write_text(updated, encoding="utf-8")

    if not written:
        return FlutterArtifactsResult(
            success=False,
            message="No Flutter files written",
            project_dir=project_dir,
            log="\n".join(log_parts),
        )

    pub_get_err = _run_pub_get(project_dir)
    if pub_get_err:
        log_parts.append(f"flutter pub get: {pub_get_err}")

    mirror_dir = _mirror_to_artifacts(project_dir)
    readme_path = project_dir / "README.md"
    readme = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
    manifest = _build_manifest(
        state=state,
        project_dir=project_dir,
        files=written,
        source=source,
        notes="; ".join(log_parts),
    )

    save_artifact("build/flutter/manifest.json", manifest)
    if readme:
        save_artifact("build/flutter/README.md", readme)

    return FlutterArtifactsResult(
        success=True,
        message=f"Flutter project ready ({len(written)} files, {source})",
        project_dir=project_dir,
        file_count=len(written),
        manifest_json=manifest,
        readme=readme,
        files=written,
        log="\n".join(log_parts),
    )
